  
version: '3.7'
services:
## - Docker file to postgres database server along with the container
  postgres:
        image: postgres:10.5
        restart: always
        environment: 
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5438:5438'
        volumes:
          - ./postgres-data:/var/lib/postgresql/data
          # copy the sql script to create tables
          - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
          # copy the sql script to fill tables
          - ./sql/fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql
## - Docker file to backend for 6200 for starting server   
  backend:
    build: ./backend
    ports:
     - "6200:6200"
    volumes:
      - ./backend:/usr/src/server
    working_dir: "/usr/src/app/server"
    depends_on: 
      - postgres
    command: ["npm", "start"]
## - Docker file overwrite the docker file
    command: ["npm", "start"]  
    frontend:         
     depends_on:       - mongodb
    build: ./ui/
   ports:
      - "3000:3000"
    volumes:
      - ./ui:/usr/src/app/ui
    depends_on:
      - backend  
      
     
